### ISSUE TITLE
Example workflows?

### ISSUE THREAD

**Issue by vsoch** [tainagdcoleman/wfchef#1]
Hiya! I just saw your paper https://www.sciencedirect.com/science/article/abs/pii/S0167739X23001711 (congrats!) and was wondering if this is the right repository for wfchef, and if there are any tutorials to try it out?

**Comment by rafaelfsilva** [comment]
Hi @vsoch, WfChef is not part of the WfCommons project and the latest code can be found here: https://github.com/wfcommons/wfcommons Thanks!

**Comment by vsoch** [comment]
Sorry to be dense - where are tutorials for wfchef?

**Comment by tainagdcoleman** [comment]
Hi @vsoch, the documentation on WfChef can be found at https://docs.wfcommons.org/en/latest/generating_workflows.html. Thank you for your interest!

**Comment by vsoch** [comment]
Perfecto - thank you to you both!
